workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter unit tests
        script: |
          flutter test || true
      - name: FORCE iOS 13.0 everywhere
        script: |
          # FORZAR iOS 13.0 en TODOS los archivos del proyecto
          find ios -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' {} \;
          find ios -name "*.pbxproj" -exec sed -i '' 's/ios[0-9]*\.[0-9]*/ios13.0/g' {} \;
          find ios -name "*.pbxproj" -exec sed -i '' 's/arm64-apple-ios[0-9]*\.[0-9]*/arm64-apple-ios13.0/g' {} \;
      - name: FORCE create new Podfile with iOS 13.0
        script: |
          # ELIMINAR completamente el Podfile existente y crear uno nuevo
          rm -f ios/Podfile
          cat > ios/Podfile << 'EOF'
          platform :ios, '13.0'

          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
            end

            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

          flutter_ios_podfile_setup

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
            
            post_install do |installer|
              installer.pods_project.targets.each do |target|
                flutter_additional_ios_build_settings(target)
                target.build_configurations.each do |config|
                  # FORZAR iOS 13.0 para TODOS los pods
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                  config.build_settings['ENABLE_BITCODE'] = 'NO'
                  config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
                  # Eliminar configuraciones problemáticas
                  config.build_settings.delete('ARCHS')
                  config.build_settings['VALID_ARCHS'] = 'arm64'
                end
              end
              
              # FORZAR configuraciones en el proyecto principal
              installer.pods_project.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
            end
          end
          EOF
      - name: NUCLEAR clean and reinstall
        script: |
          cd ios
          # ELIMINACIÓN NUCLEAR de todo
          rm -rf Pods
          rm -rf .symlinks
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/Flutter.podspec
          rm -rf Flutter/Generated.xcconfig
          rm -f Podfile.lock
          rm -rf build
          rm -rf DerivedData
          # Limpiar cache de CocoaPods
          pod cache clean --all
          # Reinstalar desde cero
          pod install --repo-update --clean-install
          cd ..
      - name: NUCLEAR Flutter clean
        script: |
          flutter clean
          rm -rf build
          flutter pub get
          flutter pub deps
      - name: Build with FORCED settings
        script: |
          # Configurar variables de entorno para forzar iOS 13.0
          export IPHONEOS_DEPLOYMENT_TARGET=13.0
          export FLUTTER_BUILD_MODE=release
          # Build final
          flutter build ios --release --no-codesign --verbose
    artifacts:
      - build/ios/iphoneos/Runner.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false