workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development  # ← CAMBIADO A DEVELOPMENT
        # Eliminamos bundle_identifier para usar el predeterminado
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      # - name: Flutter analyze
      #   script: |
      #     flutter analyze --fatal-infos
      - name: Flutter unit tests
        script: |
          flutter test || true
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false