workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter unit tests
        script: |
          flutter test || true
      - name: Simple iOS version update
        script: |
          # Solo cambiar la versión mínima a 11.0 (más compatible)
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 9.0/IPHONEOS_DEPLOYMENT_TARGET = 11.0/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0/IPHONEOS_DEPLOYMENT_TARGET = 11.0/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Simple Podfile update
        script: |
          # Solo actualizar la línea de platform en el Podfile existente
          sed -i '' "s/platform :ios, '[0-9]*\.[0-9]*'/platform :ios, '11.0'/g" ios/Podfile
      - name: Simple pod install
        script: |
          cd ios && pod install && cd ..
      - name: Simple build
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false