name: demmpro_fixed
description: Sistema de gestión de asistencia con Firebase
publish_to: 'none'
version: 5.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # File handling
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  
  # Excel
  excel: ^4.0.2
  
  # Date formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true