// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvT3l8Cu47vuCtbRFDPitIosm6kXzgMw',
    appId: '1:383624460856:web:c290d179c63d07745584cd',
    messagingSenderId: '383624460856',
    projectId: 'demmpro-2e292',
    authDomain: 'demmpro-2e292.firebaseapp.com',
    storageBucket: 'demmpro-2e292.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEvT3l8Cu47vuCtbRFDPitIosm6kXzgMw',
    appId: '1:383624460856:android:c290d179c63d07745584cd',
    messagingSenderId: '383624460856',
    projectId: 'demmpro-2e292',
    storageBucket: 'demmpro-2e292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEvT3l8Cu47vuCtbRFDPitIosm6kXzgMw',
    appId: '1:383624460856:ios:c290d179c63d07745584cd',
    messagingSenderId: '383624460856',
    projectId: 'demmpro-2e292',
    storageBucket: 'demmpro-2e292.firebasestorage.app',
    iosBundleId: 'com.demmpro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEvT3l8Cu47vuCtbRFDPitIosm6kXzgMw',
    appId: '1:383624460856:macos:c290d179c63d07745584cd',
    messagingSenderId: '383624460856',
    projectId: 'demmpro-2e292',
    storageBucket: 'demmpro-2e292.firebasestorage.app',
    iosBundleId: 'com.demmpro.app',
  );
}
